function TutorialDialog(){
	Menu
		(
			room_width/8,
			room_height/3 * 2,
			[
				["THE GOAL IS TO DEFEAT ALL OF THE ENEMY TROOPS. SELECT 2 \nTROOPS AND PLACE THEM ON YOUR SIDE OF THE MAP. TO REMOVE A \nTROOP SELECT THE BIN AND THEN CLICK ON THE TROOP YOU \nWOULD LIKE TO REMOVE. AFTER THIS LEVEL YOU WILL BE ABLE TO \nPLACE 5 TROOPS.", -1]
			],
			"TUTORIAL -",
			room_width/4 * 3,
			room_height/3
		)
}